backend:
  name: "git-gateway"
  accept_roles:
    - "admin"
    - "editor"
media_folder: "static/images"
collections:
  - name: "pages"
    label: "Pages"
    folder: "site/pages"
    identifier_field: "name"
    create: false
    delete: false
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
      - label: "Layout"
        widget: "hidden"
        name: "layout"
        default: "{{slug}}.html"
      - label: "Seo"
        name: "seo"
        widget: "object"
        collapsed: true
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
            required: false
          - label: "Description"
            name: "description"
            widget: "string"
            required: false
          - label: "Open Graph Image"
            name: "og:image"
            widget: "image"
            required: false
            media_library:
              config:
                multiple: false
          - label: "Twitter Card"
            name: "twitter:card"
            widget: "string"
            default: "summary"
            required: false
          - label: "Twitter Site"
            name: "twitter:site"
            widget: "string"
            required: false
          - label: "Twitter Creator"
            name: "twitter:creator"
            widget: "string"
            required: false
          - label: "Additional HTML tags"
            name: "additional_tags"
            widget: "text"
            required: false
  - name: "project"
    label: "Projects"
    folder: "site/project"
    create: true
    identifier_field: "name"
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - label: "Tags"
        widget: "hidden"
        name: "tags"
        default: "project"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
      - label: "Layout"
        widget: "hidden"
        name: "layout"
        default: "single-project.html"
      - label: "Seo"
        name: "seo"
        widget: "object"
        collapsed: true
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
            required: false
          - label: "Description"
            name: "description"
            widget: "string"
            required: false
          - label: "Open Graph Image"
            name: "og:image"
            widget: "image"
            required: false
            media_library:
              config:
                multiple: false
          - label: "Twitter Card"
            name: "twitter:card"
            widget: "string"
            default: "summary"
            required: false
          - label: "Twitter Site"
            name: "twitter:site"
            widget: "string"
            required: false
          - label: "Twitter Creator"
            name: "twitter:creator"
            widget: "string"
            required: false
          - label: "Additional HTML tags"
            name: "additional_tags"
            widget: "text"
            required: false
      - widget: "object"
        name: "image"
        label: "Image"
        fields:
          - widget: "image"
            name: "url"
            label: "Image"
            allow_multiple: false
            required: false
          - widget: "string"
            name: "alt"
            label: "Alt Text"
            required: false
      - widget: "object"
        name: "business-logo"
        label: "Business Logo"
        fields:
          - widget: "image"
            name: "url"
            label: "Image"
            allow_multiple: false
            required: false
          - widget: "string"
            name: "alt"
            label: "Alt Text"
            required: false
      - name: "business-name"
        label: "Business Name"
        widget: "string"
        required: false
      - name: "job-name"
        label: "Job Name"
        widget: "string"
        required: false
      - label: "Body"
        name: "body"
        widget: "markdown"
        required: false
      - name: "client-name"
        label: "Client Name"
        widget: "string"
        required: false
      - name: "client-quote"
        label: "Client Quote"
        widget: "string"
        required: false
      - name: "name"
        label: "Name"
        widget: "string"
        required: true
      - name: "created-on"
        label: "Created On"
        widget: "datetime"
        required: false
      - name: "updated-on"
        label: "Updated On"
        widget: "datetime"
        required: false
      - name: "published-on"
        label: "Published On"
        widget: "datetime"
        required: false
  - name: "tag"
    label: "Tags"
    folder: "site/tag"
    create: true
    identifier_field: "name"
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - label: "Tags"
        widget: "hidden"
        name: "tags"
        default: "tag"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
      - label: "Layout"
        widget: "hidden"
        name: "layout"
        default: "single-tag.html"
      - label: "Seo"
        name: "seo"
        widget: "object"
        collapsed: true
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
            required: false
          - label: "Description"
            name: "description"
            widget: "string"
            required: false
          - label: "Open Graph Image"
            name: "og:image"
            widget: "image"
            required: false
            media_library:
              config:
                multiple: false
          - label: "Twitter Card"
            name: "twitter:card"
            widget: "string"
            default: "summary"
            required: false
          - label: "Twitter Site"
            name: "twitter:site"
            widget: "string"
            required: false
          - label: "Twitter Creator"
            name: "twitter:creator"
            widget: "string"
            required: false
          - label: "Additional HTML tags"
            name: "additional_tags"
            widget: "text"
            required: false
      - name: "name"
        label: "Name"
        widget: "string"
        required: true
      - name: "created-on"
        label: "Created On"
        widget: "datetime"
        required: false
      - name: "updated-on"
        label: "Updated On"
        widget: "datetime"
        required: false
      - name: "published-on"
        label: "Published On"
        widget: "datetime"
        required: false
  - name: "category"
    label: "Categories"
    folder: "site/category"
    create: true
    identifier_field: "name"
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - label: "Tags"
        widget: "hidden"
        name: "tags"
        default: "category"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
      - label: "Layout"
        widget: "hidden"
        name: "layout"
        default: "single-category.html"
      - label: "Seo"
        name: "seo"
        widget: "object"
        collapsed: true
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
            required: false
          - label: "Description"
            name: "description"
            widget: "string"
            required: false
          - label: "Open Graph Image"
            name: "og:image"
            widget: "image"
            required: false
            media_library:
              config:
                multiple: false
          - label: "Twitter Card"
            name: "twitter:card"
            widget: "string"
            default: "summary"
            required: false
          - label: "Twitter Site"
            name: "twitter:site"
            widget: "string"
            required: false
          - label: "Twitter Creator"
            name: "twitter:creator"
            widget: "string"
            required: false
          - label: "Additional HTML tags"
            name: "additional_tags"
            widget: "text"
            required: false
      - name: "name"
        label: "Name"
        widget: "string"
        required: true
      - name: "created-on"
        label: "Created On"
        widget: "datetime"
        required: false
      - name: "updated-on"
        label: "Updated On"
        widget: "datetime"
        required: false
      - name: "published-on"
        label: "Published On"
        widget: "datetime"
        required: false
  - name: "career"
    label: "Careers"
    folder: "site/career"
    create: true
    identifier_field: "name"
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - label: "Tags"
        widget: "hidden"
        name: "tags"
        default: "career"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
      - label: "Layout"
        widget: "hidden"
        name: "layout"
        default: "single-career.html"
      - label: "Seo"
        name: "seo"
        widget: "object"
        collapsed: true
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
            required: false
          - label: "Description"
            name: "description"
            widget: "string"
            required: false
          - label: "Open Graph Image"
            name: "og:image"
            widget: "image"
            required: false
            media_library:
              config:
                multiple: false
          - label: "Twitter Card"
            name: "twitter:card"
            widget: "string"
            default: "summary"
            required: false
          - label: "Twitter Site"
            name: "twitter:site"
            widget: "string"
            required: false
          - label: "Twitter Creator"
            name: "twitter:creator"
            widget: "string"
            required: false
          - label: "Additional HTML tags"
            name: "additional_tags"
            widget: "text"
            required: false
      - name: "location"
        label: "Location"
        widget: "string"
        required: false
      - name: "title-name"
        label: "Title Name"
        widget: "string"
        required: false
      - label: "Body"
        name: "body"
        widget: "markdown"
        required: false
      - name: "name"
        label: "Name"
        widget: "string"
        required: true
      - name: "created-on"
        label: "Created On"
        widget: "datetime"
        required: false
      - name: "updated-on"
        label: "Updated On"
        widget: "datetime"
        required: false
      - name: "published-on"
        label: "Published On"
        widget: "datetime"
        required: false
  - name: "post"
    label: "Blog Posts"
    folder: "site/post"
    create: true
    identifier_field: "name"
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - label: "Tags"
        widget: "hidden"
        name: "tags"
        default: "post"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
      - label: "Layout"
        widget: "hidden"
        name: "layout"
        default: "single-post.html"
      - label: "Seo"
        name: "seo"
        widget: "object"
        collapsed: true
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
            required: false
          - label: "Description"
            name: "description"
            widget: "string"
            required: false
          - label: "Open Graph Image"
            name: "og:image"
            widget: "image"
            required: false
            media_library:
              config:
                multiple: false
          - label: "Twitter Card"
            name: "twitter:card"
            widget: "string"
            default: "summary"
            required: false
          - label: "Twitter Site"
            name: "twitter:site"
            widget: "string"
            required: false
          - label: "Twitter Creator"
            name: "twitter:creator"
            widget: "string"
            required: false
          - label: "Additional HTML tags"
            name: "additional_tags"
            widget: "text"
            required: false
      - label: "Body"
        name: "body"
        widget: "markdown"
        required: false
      - name: "post-summary"
        label: "Post Summary"
        widget: "text"
        required: false
      - widget: "object"
        name: "main-image"
        label: "Main Image"
        fields:
          - widget: "image"
            name: "url"
            label: "Image"
            allow_multiple: false
            required: false
          - widget: "string"
            name: "alt"
            label: "Alt Text"
            required: false
      - name: "slug-name"
        label: "Slug Name"
        widget: "string"
        required: false
      - widget: "relation"
        collection: "category"
        value_field: "category/{{slug}}.md"
        search_fields:
          - "slug"
          - "name"
        display_fields:
          - "name"
        required: true
        name: "category"
      - widget: "relation"
        collection: "tag"
        value_field: "category/{{slug}}.md"
        search_fields:
          - "slug"
          - "name"
        display_fields:
          - "name"
        required: true
        multiple: true
        name: "tag"
      - name: "written-by"
        label: "Written By"
        widget: "string"
        required: false
      - name: "name"
        label: "Name"
        widget: "string"
        required: true
      - name: "created-on"
        label: "Created On"
        widget: "datetime"
        required: false
      - name: "updated-on"
        label: "Updated On"
        widget: "datetime"
        required: false
      - name: "published-on"
        label: "Published On"
        widget: "datetime"
        required: false
  - name: "service"
    label: "Services"
    folder: "site/service"
    create: true
    identifier_field: "name"
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - label: "Tags"
        widget: "hidden"
        name: "tags"
        default: "service"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
      - label: "Layout"
        widget: "hidden"
        name: "layout"
        default: "single-service.html"
      - label: "Seo"
        name: "seo"
        widget: "object"
        collapsed: true
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
            required: false
          - label: "Description"
            name: "description"
            widget: "string"
            required: false
          - label: "Open Graph Image"
            name: "og:image"
            widget: "image"
            required: false
            media_library:
              config:
                multiple: false
          - label: "Twitter Card"
            name: "twitter:card"
            widget: "string"
            default: "summary"
            required: false
          - label: "Twitter Site"
            name: "twitter:site"
            widget: "string"
            required: false
          - label: "Twitter Creator"
            name: "twitter:creator"
            widget: "string"
            required: false
          - label: "Additional HTML tags"
            name: "additional_tags"
            widget: "text"
            required: false
      - widget: "object"
        name: "attachment"
        label: "Attachment"
        fields:
          - widget: "file"
            name: "url"
            label: "File"
            allow_multiple: false
            required: false
      - name: "attachment-name"
        label: "Attachment Name"
        widget: "string"
        required: false
      - label: "Body"
        name: "body"
        widget: "markdown"
        required: false
      - name: "name"
        label: "Name"
        widget: "string"
        required: true
      - name: "created-on"
        label: "Created On"
        widget: "datetime"
        required: false
      - name: "updated-on"
        label: "Updated On"
        widget: "datetime"
        required: false
      - name: "published-on"
        label: "Published On"
        widget: "datetime"
        required: false
